openapi: 3.0.0
info:
  title: mockdata OpenAPI
  description: mockdata Service
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: Local Dev Server
paths:
  /Mockdata/create:
    post:
      tags:
        - Mockdata
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vital_type:
                  type: string
                count:
                  type: integer
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
          $ref: "#/components/responses/UnauthorizedError"
        "404":
          $ref: "#/components/responses/ResourceNotFoundError"
        "422":
          $ref: "#/components/responses/UnAcceptableInputs"
  /Mockdata/get:
    get:
      tags:
        - Mockdata
      parameters:
        - $ref: "#/components/parameters/idParam"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        "401":
            $ref: "#/components/responses/UnauthorizedError"
        "404":
            $ref: "#/components/responses/ResourceNotFoundError"
        "422":
            $ref: "#/components/responses/UnAcceptableInputs"
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    ResourceNotFoundError:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
    UnauthorizedError:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
    UnAcceptableInputs:
      description: Invalid Inputs
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/MessageDto"
  parameters:
    idParam:
      name: vital_type
      in: query
      required: true
      schema:
        type: string
  schemas:
    MessageDto:
      type: object
      properties:
        message:
          type: string
      required:
        - message