openapi: 3.0.0
info:
  title: mockdata OpenAPI
  description: mockdata Service
  version: 0.0.1
servers:
  - url: http://localhost:8080/
    description: Local Dev Server
paths:
  /Mockdata/create:
    post:
      tags:
        - Mockdata
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                vital_type:
                  type: string
                count:
                  type: integer
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /Mockdata/get:
    get:
      tags:
        - Mockdata
      parameters:
        - $ref: "#/components/parameters/idParam"
      responses:
        "201":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
components:
  parameters:
    idParam:
      name: vital_type
      in: query
      required: true
      schema:
        type: string
  schemas:
    MessageDto:
      type: object
      properties:
        message:
          type: string
      required:
        - message