# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MockdataCreatePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, vital_type=None, patient_id=None):  # noqa: E501
        """MockdataCreatePostRequest - a model defined in OpenAPI

        :param vital_type: The vital_type of this MockdataCreatePostRequest.  # noqa: E501
        :type vital_type: str
        :param patient_id: The patient_id of this MockdataCreatePostRequest.  # noqa: E501
        :type patient_id: str
        """
        self.openapi_types = {
            'vital_type': str,
            'patient_id': str
        }

        self.attribute_map = {
            'vital_type': 'vital_type',
            'patient_id': 'patientId'
        }

        self._vital_type = vital_type
        self._patient_id = patient_id

    @classmethod
    def from_dict(cls, dikt) -> 'MockdataCreatePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _Mockdata_create_post_request of this MockdataCreatePostRequest.  # noqa: E501
        :rtype: MockdataCreatePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vital_type(self):
        """Gets the vital_type of this MockdataCreatePostRequest.


        :return: The vital_type of this MockdataCreatePostRequest.
        :rtype: str
        """
        return self._vital_type

    @vital_type.setter
    def vital_type(self, vital_type):
        """Sets the vital_type of this MockdataCreatePostRequest.


        :param vital_type: The vital_type of this MockdataCreatePostRequest.
        :type vital_type: str
        """

        self._vital_type = vital_type

    @property
    def patient_id(self):
        """Gets the patient_id of this MockdataCreatePostRequest.


        :return: The patient_id of this MockdataCreatePostRequest.
        :rtype: str
        """
        return self._patient_id

    @patient_id.setter
    def patient_id(self, patient_id):
        """Sets the patient_id of this MockdataCreatePostRequest.


        :param patient_id: The patient_id of this MockdataCreatePostRequest.
        :type patient_id: str
        """

        self._patient_id = patient_id
