# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model_ import Model
from openapi_server import util


class MockdataCreatePostRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, vital_type=None, count=None):  # noqa: E501
        """MockdataCreatePostRequest - a model defined in OpenAPI

        :param vital_type: The vital_type of this MockdataCreatePostRequest.  # noqa: E501
        :type vital_type: str
        :param count: The count of this MockdataCreatePostRequest.  # noqa: E501
        :type count: int
        """
        self.openapi_types = {
            'vital_type': str,
            'count': int
        }

        self.attribute_map = {
            'vital_type': 'vital_type',
            'count': 'count'
        }

        self._vital_type = vital_type
        self._count = count

    @classmethod
    def from_dict(cls, dikt) -> 'MockdataCreatePostRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The _Mockdata_create_post_request of this MockdataCreatePostRequest.  # noqa: E501
        :rtype: MockdataCreatePostRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def vital_type(self):
        """Gets the vital_type of this MockdataCreatePostRequest.


        :return: The vital_type of this MockdataCreatePostRequest.
        :rtype: str
        """
        return self._vital_type

    @vital_type.setter
    def vital_type(self, vital_type):
        """Sets the vital_type of this MockdataCreatePostRequest.


        :param vital_type: The vital_type of this MockdataCreatePostRequest.
        :type vital_type: str
        """

        self._vital_type = vital_type

    @property
    def count(self):
        """Gets the count of this MockdataCreatePostRequest.


        :return: The count of this MockdataCreatePostRequest.
        :rtype: int
        """
        return self._count

    @count.setter
    def count(self, count):
        """Sets the count of this MockdataCreatePostRequest.


        :param count: The count of this MockdataCreatePostRequest.
        :type count: int
        """

        self._count = count
