openapi: 3.0.0
info:
  description: mockdata Service
  title: mockdata OpenAPI
  version: 0.0.1
servers:
- description: Local Dev Server
  url: http://localhost:8080/
paths:
  /Mockdata/create:
    post:
      operationId: mockdata_create_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/_Mockdata_create_post_request'
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_Mockdata_create_post_201_response'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDto'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDto'
          description: The specified resource was not found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDto'
          description: Invalid Inputs
      tags:
      - Mockdata
      x-openapi-router-controller: openapi_server.controllers.mockdata_controller
  /Mockdata/get:
    get:
      operationId: mockdata_get_get
      parameters:
      - explode: true
        in: query
        name: vital_type
        required: true
        schema:
          type: string
        style: form
      - explode: true
        in: query
        name: patientId
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_Mockdata_create_post_201_response'
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDto'
          description: Unauthorized
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDto'
          description: The specified resource was not found
        "422":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageDto'
          description: Invalid Inputs
      tags:
      - Mockdata
      x-openapi-router-controller: openapi_server.controllers.mockdata_controller
components:
  parameters:
    patientIdParam:
      explode: true
      in: query
      name: patientId
      required: true
      schema:
        type: string
      style: form
    idParam:
      explode: true
      in: query
      name: vital_type
      required: true
      schema:
        type: string
      style: form
  responses:
    ResourceNotFoundError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageDto'
      description: The specified resource was not found
    UnauthorizedError:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageDto'
      description: Unauthorized
    UnAcceptableInputs:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/MessageDto'
      description: Invalid Inputs
  schemas:
    MessageDto:
      properties:
        message:
          title: message
          type: string
      required:
      - message
      title: MessageDto
      type: object
    _Mockdata_create_post_request:
      properties:
        vital_type:
          title: vital_type
          type: string
        patientId:
          title: patientId
          type: string
      title: _Mockdata_create_post_request
      type: object
    _Mockdata_create_post_201_response:
      example:
        message: message
      properties:
        message:
          title: message
          type: string
      title: _Mockdata_create_post_201_response
      type: object
  securitySchemes:
    bearerAuth:
      scheme: bearer
      type: http
      x-bearerInfoFunc: openapi_server.controllers.security_controller_.info_from_bearerAuth
